name: Docker

on:
    pull_request:
      branches: [ 'main']
      paths:
        - '.github/workflows/docker.yml'
        - 'src/pytest_celery/vendors/worker/**'
        - "**.py"
        - "**.txt"
        - "**.toml"
        - "tox.ini"
        - 'Dockerfile'
        - "poetry.lock"
    push:
      branches: [ 'main']
      paths:
        - '.github/workflows/docker.yml'
        - 'src/pytest_celery/vendors/worker/**'
        - "**.py"
        - "**.txt"
        - "**.toml"
        - "tox.ini"
        - 'Dockerfile'
        - "poetry.lock"


jobs:
  build-worker:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v5
    - name: Build Celery Worker
      run: cd src/pytest_celery/vendors/worker && docker build -t pytest-celery-worker .
